name: Generate 120 times `Foo is not Bar`

on:
  push:
  schedule:
    - cron: '30 5 * * 1,3'
  workflow_dispatch:

jobs:
  generate-search-string:
    runs-on: ubuntu-latest
    env:
      SEARCH_STRING: 'Foo is not Bar'
      MAX_SEARCH: '120'


    steps:
      - uses: actions/checkout@v4

      - name: Generating ${{ env.MAX_SEARCH }} times '${{ env.SEARCH_STRING }}'
        run: |
          echo " Generating ${{ env.MAX_SEARCH }} times '${{ env.SEARCH_STRING }}' "
          i=1
          while [ $i -le ${{ env.MAX_SEARCH }} ]; do
            echo "Iteration $i: '${{ env.SEARCH_STRING }}'"
            ((i++))
          done
        shell: bash
